# Generated by Django 6.1 on 2026-09-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matchmaking", "0002_alter_matchmakingentry_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchmakingentry",
            name="rating",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
