# Generated by Django 6.1 on 2026-10-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("matchmaking", "0003_matchmakingentry_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchmakingentry",
            name="pending_timeout_task_id",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
