# Generated by Django 6.1 on 2026-10-01 10:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("matchmaking", "0004_matchmakingentry_pending_timeout_task_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="matchmakingentry",
            old_name="pending_timeout_task_id",
            new_name="pending_task_id",
        ),
    ]
