# Generated by Django 6.1 on 2026-08-18 10:13

from django.db import migrations, models

import accounts.utilis


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationCode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "code",
                    models.CharField(default=accounts.utilis.generate_verification_code, max_length=6, unique=True),
                ),
                ("email", models.EmailField(max_length=150, unique=True)),
            ],
        ),
    ]
