# Generated by Django 6.1 on 2026-08-23 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import games.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeControl",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "category",
                    models.CharField(
                        choices=[("bullet", "Bullet"), ("blitz", "Blitz"), ("rapid", "Rapid")], max_length=6
                    ),
                ),
                ("initial_time_seconds", models.PositiveIntegerField()),
                ("increment_seconds", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("white_won", "White Won"),
                            ("black_won", "Black Won"),
                            ("draw", "Draw"),
                            ("in_progress", "In Progress"),
                        ],
                        max_length=11,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "black_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games_as_black",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "white_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games_as_white",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "time_control",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="games.timecontrol"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Move",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ply_number", models.PositiveIntegerField()),
                ("from_square", models.CharField(max_length=2, validators=[games.validators.validate_move])),
                ("to_square", models.CharField(max_length=2, validators=[games.validators.validate_move])),
                (
                    "piece",
                    models.CharField(
                        choices=[
                            ("P", "Pawn"),
                            ("N", "Knight"),
                            ("B", "Bishop"),
                            ("R", "Rook"),
                            ("Q", "Queen"),
                            ("K", "King"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "promotion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("P", "Pawn"),
                            ("N", "Knight"),
                            ("B", "Bishop"),
                            ("R", "Rook"),
                            ("Q", "Queen"),
                            ("K", "King"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("resulting_fen", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("game", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="games.game")),
                ("player", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("game", "ply_number"), name="game_unique_player")],
            },
        ),
        migrations.CreateModel(
            name="UserRating",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "category",
                    models.CharField(
                        choices=[("bullet", "Bullet"), ("blitz", "Blitz"), ("rapid", "Rapid")], max_length=6
                    ),
                ),
                ("rating", models.PositiveIntegerField(default=300)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("user", "category"), name="user_rating_unique_category")
                ],
            },
        ),
    ]
