# Generated by Django 6.1 on 2026-08-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="black_connected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="game",
            name="status",
            field=models.CharField(
                choices=[("waiting", "Waiting"), ("in_progress", "In Progress"), ("finished", "Finished")],
                default="waiting",
                max_length=11,
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="white_connected",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="game",
            name="result",
            field=models.CharField(
                blank=True,
                choices=[("white_won", "White Won"), ("black_won", "Black Won"), ("draw", "Draw")],
                max_length=9,
                null=True,
            ),
        ),
    ]
