# Generated by Django 6.1 on 2026-09-01 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_game_black_connected_game_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="time_control",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="time_control", to="games.timecontrol"
            ),
        ),
    ]
