# Generated by Django 6.1 on 2026-08-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_alter_userrating_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="black_time_remaining",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="current_turn_started_at",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="white_time_remaining",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
