# Generated by Django 6.1 on 2026-09-14 19:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_game_pending_timeout_task_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="pending_timeout_task_id",
        ),
    ]
