# Generated by Django 6.1 on 2026-09-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0003_remove_game_pending_timeout_task_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="pending_timeout_task_id",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
