# Generated by Django 6.1 on 2026-09-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0003_alter_game_time_control"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="draw_offered_by",
            field=models.CharField(
                blank=True, choices=[("white", "White"), ("black", "Black")], max_length=5, null=True
            ),
        ),
    ]
