# Generated by Django 6.1 on 2026-08-26 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0003_game_black_time_remaining_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="move",
            name="game",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="moves", to="games.game"),
        ),
    ]
