# Generated by Django 6.1 on 2026-09-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0004_game_pending_timeout_task_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("checkmate", "Checkmate"),
                    ("stalemate", "Stalemate"),
                    ("timeout", "Timeout"),
                    ("surrender", "Surrender"),
                    ("draw_accepted", "Draw accepted"),
                    ("insufficient_material", "Insufficient material"),
                    ("fifty_move_rule", "Fifty-move rule"),
                    ("threefold_repetition", "Threefold repetition"),
                ],
                max_length=21,
                null=True,
            ),
        ),
    ]
